logging:
  level:
    root: INFO
source:
  config:
    url: 127.0.0.1:9092
    group: newsgroup
elasticsearch:
  host: 127.0.0.1
  port: 9200
  username: admin
  password: "123456"
spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
    mongodb:
      uri: mongodb://admin:123456@127.0.0.1:27017/sina_news?authSource=admin
  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 86400000
      # 缓存null值，防止缓存穿透
      cache-null-values: true

